name: flutter_degen_annotations
version: 1.2.0+3
homepage: https://github.com/SunnyApp/flutter_degen_annotations
documentation: https://github.com/SunnyApp/flutter_degen
description: Annotations for flutter_degen project
repository: https://github.com/SunnyApp/flutter_degen_annotations
issue_tracker: https://github.com/SunnyApp/flutter_degen/isssues
environment: 
  sdk: '>=2.7.0 <3.0.0'
dev_dependencies: 
  test: any
  test_coverage: any
  effective_dart: any
  build_test: any
authors: 
  - Eric Martineau <eric@sunnyapp.co>
