name: flutter_degen_annotations
version: 1.7.0
homepage: https://github.com/SunnyApp/flutter_degen_annotations
documentation: https://github.com/SunnyApp/flutter_degen
description: Annotations for flutter_degen project
repository: https://github.com/SunnyApp/flutter_degen_annotations
issue_tracker: https://github.com/SunnyApp/flutter_degen/isssues
environment: 
  sdk: '>=2.15.0 <3.0.0'
dev_dependencies: 
  test: ^1.21.1
  pedantic: ^1.11.1
  effective_dart: ^1.3.2
  build_test: ^2.1.5
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
